# Generated by Django 5.1.5 on 2025-02-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm2', '0002_alter_business_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='business',
            table=None,
        ),
    ]
