name: Build and deploy container app to Azure Web App - django-etl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_USERNAME }}  # Replace with Docker Hub username secret
        password: ${{ secrets.DOCKER_PASSWORD }}  # Replace with Docker Hub password or access token secret

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.DOCKER_USERNAME }}/simplysowj/django-backend:latest
        file: ./backend/apiview/orm1/Dockerfile  # Ensure this path is correct

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'django-etl'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5246959b830f4aaca218f7e9b5c37394 }}  # Azure Publish Profile secret
        images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/simplysowj/django-backend:latest'
