name: Build and deploy Python app to Azure Web App - etl-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd backend/apiview/orm1/
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd backend/apiview/orm1/
          zip -r ../../python-app.zip .  # Ensure ZIP is created correctly

      - name: Debug - List Files Before Upload
        run: ls -R  # Check if python-app.zip exists

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: python-app.zip  # Corrected path

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: List Available Artifacts
        run: ls -R /home/runner/work/_temp/  # Debugging step

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Debug - List Downloaded Files
        run: ls -R  # Verify artifact is downloaded

      - name: Unzip artifact for deployment
        run: |
          unzip python-app.zip -d app  # Extract into `app` directory
          ls -R app/  # Verify files

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'etl-backend'
          slot-name: 'Production'
          package: ./app  # Use the correct extracted path
